version: '3'

services:

  dbpostgresql:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Lfjk4583
      - POSTGRES_USER=quiron
      - POSTGRES_DB=cronida

  springboot:
    image: openjdk:11
    container_name: spring
    build:
      context: spring
      dockerfile: Dockerfile
    ports:
      - "9088:9088"
    restart: always
    depends_on:
      - dbpostgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/cronida
      SPRING_DATASOURCE_USERNAME: quiron
      SPRING_DATASOURCE_PASSWORD: Lfjk4583

  frontend:
    build:
      context: vue
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    volumes: 
      - .:/home/node/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true