version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-db:/var/lib/mysql/cronida

  backend:
    image: backend
    ports:
      - "9088:9088"
    depends_on:
      - mysql-db
    volumes:
      - .:/home/backend/quiron:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: openjdk:11
    depends_on:
      - mysql-db
    volumes:
      - backend-home:/home/mmuni/GIT/quiron_challenge/spring
    init: true
    command: ['sleep', '365d']

  frontend:
    image: frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql-db:
  backend-home:
  frontend-home:
